#######################
# Theme Customization #
#######################

title: 윤준필                             # used in <title> tag & site header
author: 윤준필                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  안녕하세요 , 저는 서울에 살고 있는 백엔드 개발자 지망생 윤준필이라고 해요.
  모두 즐겁게 코딩해봐요 ^^
slogan: Porsche 911 은 나의 것!                           # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: https://leepnujnooy.github.io              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://leepnujnooy.github.io # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/rlue/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Solana
    teaser: A responsive blog template written in Sass and vanilla JavaScript.
    url: https://github.com/rlue/jekyll-solana
    role: Creator
    category: Frontend Dev
  - title: Cortana
    teaser: A talking robot. Now available on Google Play?
    url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
    role: Core Team
    category: NLP
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
